"""
Embedded J1939 Engine ECU specification.

Replaces the need for the SAE J1939 Digital Annex spreadsheet.
Defines common engine PGNs and SPNs with their signal properties
as documented in SAE J1939-71 (Application Layer).
"""


def get_engine_j1939_spec():
    """Return a J1939 spec dict in the same format that J1939DA.parse_J1939DA produces."""

    spec = {}

    # ─── PGN 61444 (0xF004) — EEC1: Electronic Engine Controller 1 ───
    spec[61444] = {
        'Parameter Group Label': 'Electronic Engine Controller 1',
        'Acronym': 'EEC1',
        'PGN Description': 'Engine speed, torque, and demand signals.',
        'PGN Data Length': 8,
        'Default Priority': 3,
        'Transmission Rate': '10 ms',
        'transmission_rate_ms': 10,
        'SPNs': {
            899: {
                'SPN Name': 'Engine Torque Mode',
                'SPN Description': (
                    '0 Low idle governor/no request\n'
                    '1 Accelerator pedal/operator selection\n'
                    '2 Cruise control\n'
                    '3 PTO governor\n'
                    '4 Road speed governor\n'
                    '5 ASR control\n'
                    '6 Transmission control\n'
                    '7 ABS control\n'
                    '8 Torque limiting\n'
                    '9 High speed governor\n'
                    '10 Braking system\n'
                    '11 Remote accelerator\n'
                    '12 Service procedure\n'
                    '13 Not defined\n'
                    '14 Other\n'
                    '15 Not available'
                ),
                'SPN Position in PGN': '1.1',
                'SPN Length': '4 bits',
                'Resolution': 'bit-mapped',
                'Offset': '0',
                'Data Range': 'bit-mapped',
                'Operational Range': None,
                'Units': 'bit',
                'start_byte': 0,
                'start_bit': 0,
                'length_bits': 4,
                'scale': 'ENUM',
                'n_decimals': 0,
                'offset': 0,
                'min_value': 0,
                'max_value': 15,
                'unit': '',
                'discrete_values': {
                    0: 'Low idle governor/no request',
                    1: 'Accelerator pedal/operator selection',
                    2: 'Cruise control',
                    3: 'PTO governor',
                    4: 'Road speed governor',
                    5: 'ASR control',
                    6: 'Transmission control',
                    7: 'ABS control',
                    8: 'Torque limiting',
                    9: 'High speed governor',
                    10: 'Braking system',
                    11: 'Remote accelerator',
                    12: 'Service procedure',
                    13: 'Not defined',
                    14: 'Other',
                    15: 'Not available',
                },
            },
            513: {
                'SPN Name': "Driver's Demand Engine - Percent Torque",
                'SPN Description': 'The requested torque output of the engine by the driver.',
                'SPN Position in PGN': '2',
                'SPN Length': '8 bits',
                'Resolution': '1 %/bit',
                'Offset': '-125',
                'Data Range': '-125 to 125 %',
                'Operational Range': None,
                'Units': '%',
                'start_byte': 1,
                'start_bit': 0,
                'length_bits': 8,
                'scale': 1,
                'n_decimals': 0,
                'offset': -125,
                'min_value': -125,
                'max_value': 125,
                'unit': '%',
            },
            190: {
                'SPN Name': 'Engine Speed',
                'SPN Description': 'Actual engine speed.',
                'SPN Position in PGN': '4-5',
                'SPN Length': '16 bits',
                'Resolution': '0.125 rpm/bit',
                'Offset': '0',
                'Data Range': '0 to 8031.875 rpm',
                'Operational Range': None,
                'Units': 'rpm',
                'start_byte': 3,
                'start_bit': 0,
                'length_bits': 16,
                'scale': 0.125,
                'n_decimals': 3,
                'offset': 0,
                'min_value': 0,
                'max_value': 8031.875,
                'unit': 'rpm',
            },
            512: {
                'SPN Name': 'Actual Engine - Percent Torque',
                'SPN Description': 'The calculated output torque of the engine.',
                'SPN Position in PGN': '3',
                'SPN Length': '8 bits',
                'Resolution': '1 %/bit',
                'Offset': '-125',
                'Data Range': '-125 to 125 %',
                'Operational Range': None,
                'Units': '%',
                'start_byte': 2,
                'start_bit': 0,
                'length_bits': 8,
                'scale': 1,
                'n_decimals': 0,
                'offset': -125,
                'min_value': -125,
                'max_value': 125,
                'unit': '%',
            },
            1483: {
                'SPN Name': 'Source Address of Controlling Device for Engine Control',
                'SPN Description': 'The source address of the controlling device.',
                'SPN Position in PGN': '6',
                'SPN Length': '8 bits',
                'Resolution': '1/bit',
                'Offset': '0',
                'Data Range': '0 to 255',
                'Operational Range': None,
                'Units': None,
                'start_byte': 5,
                'start_bit': 0,
                'length_bits': 8,
                'scale': 1,
                'n_decimals': 0,
                'offset': 0,
                'min_value': 0,
                'max_value': 255,
                'unit': None,
            },
        },
    }

    # ─── PGN 61443 (0xF003) — EEC2: Electronic Engine Controller 2 ───
    spec[61443] = {
        'Parameter Group Label': 'Electronic Engine Controller 2',
        'Acronym': 'EEC2',
        'PGN Description': 'Accelerator pedal and engine load signals.',
        'PGN Data Length': 8,
        'Default Priority': 3,
        'Transmission Rate': '50 ms',
        'transmission_rate_ms': 50,
        'SPNs': {
            91: {
                'SPN Name': 'Accelerator Pedal Position 1',
                'SPN Description': 'The ratio of actual position of the pedal to maximum position.',
                'SPN Position in PGN': '2',
                'SPN Length': '8 bits',
                'Resolution': '0.4 %/bit',
                'Offset': '0',
                'Data Range': '0 to 100 %',
                'Operational Range': None,
                'Units': '%',
                'start_byte': 1,
                'start_bit': 0,
                'length_bits': 8,
                'scale': 0.4,
                'n_decimals': 1,
                'offset': 0,
                'min_value': 0,
                'max_value': 100,
                'unit': '%',
            },
            92: {
                'SPN Name': 'Engine Percent Load At Current Speed',
                'SPN Description': 'The ratio of actual to maximum engine torque at current speed.',
                'SPN Position in PGN': '3',
                'SPN Length': '8 bits',
                'Resolution': '1 %/bit',
                'Offset': '0',
                'Data Range': '0 to 250 %',
                'Operational Range': None,
                'Units': '%',
                'start_byte': 2,
                'start_bit': 0,
                'length_bits': 8,
                'scale': 1,
                'n_decimals': 0,
                'offset': 0,
                'min_value': 0,
                'max_value': 250,
                'unit': '%',
            },
            974: {
                'SPN Name': 'Remote Accelerator Pedal Position',
                'SPN Description': 'The ratio of actual remote accelerator position to maximum position.',
                'SPN Position in PGN': '4',
                'SPN Length': '8 bits',
                'Resolution': '0.4 %/bit',
                'Offset': '0',
                'Data Range': '0 to 100 %',
                'Operational Range': None,
                'Units': '%',
                'start_byte': 3,
                'start_bit': 0,
                'length_bits': 8,
                'scale': 0.4,
                'n_decimals': 1,
                'offset': 0,
                'min_value': 0,
                'max_value': 100,
                'unit': '%',
            },
        },
    }

    # ─── PGN 65262 (0xFEEE) — ET1: Engine Temperature 1 ───
    spec[65262] = {
        'Parameter Group Label': 'Engine Temperature 1',
        'Acronym': 'ET1',
        'PGN Description': 'Engine temperature parameters.',
        'PGN Data Length': 8,
        'Default Priority': 6,
        'Transmission Rate': '1 s',
        'transmission_rate_ms': 1000,
        'SPNs': {
            110: {
                'SPN Name': 'Engine Coolant Temperature',
                'SPN Description': 'Temperature of liquid found in engine cooling system.',
                'SPN Position in PGN': '1',
                'SPN Length': '8 bits',
                'Resolution': '1 deg C/bit',
                'Offset': '-40',
                'Data Range': '-40 to 210 deg C',
                'Operational Range': None,
                'Units': 'deg C',
                'start_byte': 0,
                'start_bit': 0,
                'length_bits': 8,
                'scale': 1,
                'n_decimals': 0,
                'offset': -40,
                'min_value': -40,
                'max_value': 210,
                'unit': 'deg C',
            },
            174: {
                'SPN Name': 'Fuel Temperature 1',
                'SPN Description': 'Temperature of fuel entering the injection system.',
                'SPN Position in PGN': '2',
                'SPN Length': '8 bits',
                'Resolution': '1 deg C/bit',
                'Offset': '-40',
                'Data Range': '-40 to 210 deg C',
                'Operational Range': None,
                'Units': 'deg C',
                'start_byte': 1,
                'start_bit': 0,
                'length_bits': 8,
                'scale': 1,
                'n_decimals': 0,
                'offset': -40,
                'min_value': -40,
                'max_value': 210,
                'unit': 'deg C',
            },
            175: {
                'SPN Name': 'Engine Oil Temperature 1',
                'SPN Description': 'Temperature of the engine lubricant.',
                'SPN Position in PGN': '3-4',
                'SPN Length': '16 bits',
                'Resolution': '0.03125 deg C/bit',
                'Offset': '-273',
                'Data Range': '-273 to 1735 deg C',
                'Operational Range': None,
                'Units': 'deg C',
                'start_byte': 2,
                'start_bit': 0,
                'length_bits': 16,
                'scale': 0.03125,
                'n_decimals': 5,
                'offset': -273,
                'min_value': -273,
                'max_value': 1735,
                'unit': 'deg C',
            },
        },
    }

    # ─── PGN 65263 (0xFEEF) — EFL/P1: Engine Fluid Level/Pressure 1 ───
    spec[65263] = {
        'Parameter Group Label': 'Engine Fluid Level/Pressure 1',
        'Acronym': 'EFL/P1',
        'PGN Description': 'Engine fluid levels and pressures.',
        'PGN Data Length': 8,
        'Default Priority': 6,
        'Transmission Rate': '500 ms',
        'transmission_rate_ms': 500,
        'SPNs': {
            94: {
                'SPN Name': 'Fuel Delivery Pressure',
                'SPN Description': 'Gage pressure of fuel in the fuel delivery system.',
                'SPN Position in PGN': '1',
                'SPN Length': '8 bits',
                'Resolution': '4 kPa/bit',
                'Offset': '0',
                'Data Range': '0 to 1000 kPa',
                'Operational Range': None,
                'Units': 'kPa',
                'start_byte': 0,
                'start_bit': 0,
                'length_bits': 8,
                'scale': 4,
                'n_decimals': 0,
                'offset': 0,
                'min_value': 0,
                'max_value': 1000,
                'unit': 'kPa',
            },
            22: {
                'SPN Name': 'Engine Extended Crankcase Blow-by Pressure',
                'SPN Description': 'Gage pressure of air inside the crankcase.',
                'SPN Position in PGN': '2',
                'SPN Length': '8 bits',
                'Resolution': '0.05 kPa/bit',
                'Offset': '0',
                'Data Range': '0 to 12.5 kPa',
                'Operational Range': None,
                'Units': 'kPa',
                'start_byte': 1,
                'start_bit': 0,
                'length_bits': 8,
                'scale': 0.05,
                'n_decimals': 2,
                'offset': 0,
                'min_value': 0,
                'max_value': 12.5,
                'unit': 'kPa',
            },
            100: {
                'SPN Name': 'Engine Oil Pressure',
                'SPN Description': 'Gage pressure of oil in the engine lubrication system.',
                'SPN Position in PGN': '4',
                'SPN Length': '8 bits',
                'Resolution': '4 kPa/bit',
                'Offset': '0',
                'Data Range': '0 to 1000 kPa',
                'Operational Range': None,
                'Units': 'kPa',
                'start_byte': 3,
                'start_bit': 0,
                'length_bits': 8,
                'scale': 4,
                'n_decimals': 0,
                'offset': 0,
                'min_value': 0,
                'max_value': 1000,
                'unit': 'kPa',
            },
            109: {
                'SPN Name': 'Coolant Pressure',
                'SPN Description': 'Gage pressure of the coolant in the cooling system.',
                'SPN Position in PGN': '6',
                'SPN Length': '8 bits',
                'Resolution': '2 kPa/bit',
                'Offset': '0',
                'Data Range': '0 to 500 kPa',
                'Operational Range': None,
                'Units': 'kPa',
                'start_byte': 5,
                'start_bit': 0,
                'length_bits': 8,
                'scale': 2,
                'n_decimals': 0,
                'offset': 0,
                'min_value': 0,
                'max_value': 500,
                'unit': 'kPa',
            },
        },
    }

    # ─── PGN 65266 (0xFEF2) — LFE1: Fuel Economy (Liquid) ───
    spec[65266] = {
        'Parameter Group Label': 'Fuel Economy (Liquid)',
        'Acronym': 'LFE1',
        'PGN Description': 'Fuel rate and economy information.',
        'PGN Data Length': 8,
        'Default Priority': 6,
        'Transmission Rate': '100 ms',
        'transmission_rate_ms': 100,
        'SPNs': {
            183: {
                'SPN Name': 'Engine Fuel Rate',
                'SPN Description': 'Volume of fuel consumed per unit of time.',
                'SPN Position in PGN': '1-2',
                'SPN Length': '16 bits',
                'Resolution': '0.05 L/h per bit',
                'Offset': '0',
                'Data Range': '0 to 3212.75 L/h',
                'Operational Range': None,
                'Units': 'L/h',
                'start_byte': 0,
                'start_bit': 0,
                'length_bits': 16,
                'scale': 0.05,
                'n_decimals': 2,
                'offset': 0,
                'min_value': 0,
                'max_value': 3212.75,
                'unit': 'L/h',
            },
            184: {
                'SPN Name': 'Instantaneous Fuel Economy',
                'SPN Description': 'Current fuel economy at current vehicle speed.',
                'SPN Position in PGN': '3-4',
                'SPN Length': '16 bits',
                'Resolution': '1/512 km/L per bit',
                'Offset': '0',
                'Data Range': '0 to 125.5 km/L',
                'Operational Range': None,
                'Units': 'km/L',
                'start_byte': 2,
                'start_bit': 0,
                'length_bits': 16,
                'scale': 1 / 512,
                'n_decimals': 4,
                'offset': 0,
                'min_value': 0,
                'max_value': 125.5,
                'unit': 'km/L',
            },
        },
    }

    # ─── PGN 65270 (0xFEF6) — IC1: Inlet/Exhaust Conditions 1 ───
    spec[65270] = {
        'Parameter Group Label': 'Inlet/Exhaust Conditions 1',
        'Acronym': 'IC1',
        'PGN Description': 'Engine inlet and exhaust conditions.',
        'PGN Data Length': 8,
        'Default Priority': 6,
        'Transmission Rate': '500 ms',
        'transmission_rate_ms': 500,
        'SPNs': {
            102: {
                'SPN Name': 'Boost Pressure',
                'SPN Description': 'Gage pressure of air measured downstream of the compressor.',
                'SPN Position in PGN': '2',
                'SPN Length': '8 bits',
                'Resolution': '2 kPa/bit',
                'Offset': '0',
                'Data Range': '0 to 500 kPa',
                'Operational Range': None,
                'Units': 'kPa',
                'start_byte': 1,
                'start_bit': 0,
                'length_bits': 8,
                'scale': 2,
                'n_decimals': 0,
                'offset': 0,
                'min_value': 0,
                'max_value': 500,
                'unit': 'kPa',
            },
            105: {
                'SPN Name': 'Intake Manifold 1 Temperature',
                'SPN Description': 'Temperature of pre-combustion air in the intake manifold.',
                'SPN Position in PGN': '3',
                'SPN Length': '8 bits',
                'Resolution': '1 deg C/bit',
                'Offset': '-40',
                'Data Range': '-40 to 210 deg C',
                'Operational Range': None,
                'Units': 'deg C',
                'start_byte': 2,
                'start_bit': 0,
                'length_bits': 8,
                'scale': 1,
                'n_decimals': 0,
                'offset': -40,
                'min_value': -40,
                'max_value': 210,
                'unit': 'deg C',
            },
            106: {
                'SPN Name': 'Air Inlet Pressure',
                'SPN Description': 'Air pressure at the air filter inlet.',
                'SPN Position in PGN': '4',
                'SPN Length': '8 bits',
                'Resolution': '2 kPa/bit',
                'Offset': '0',
                'Data Range': '0 to 500 kPa',
                'Operational Range': None,
                'Units': 'kPa',
                'start_byte': 3,
                'start_bit': 0,
                'length_bits': 8,
                'scale': 2,
                'n_decimals': 0,
                'offset': 0,
                'min_value': 0,
                'max_value': 500,
                'unit': 'kPa',
            },
        },
    }

    # ─── PGN 65271 (0xFEF7) — VEP1: Vehicle Electrical Power 1 ───
    spec[65271] = {
        'Parameter Group Label': 'Vehicle Electrical Power 1',
        'Acronym': 'VEP1',
        'PGN Description': 'Battery and charging system parameters.',
        'PGN Data Length': 8,
        'Default Priority': 6,
        'Transmission Rate': '1 s',
        'transmission_rate_ms': 1000,
        'SPNs': {
            168: {
                'SPN Name': 'Battery Potential / Power Input 1',
                'SPN Description': 'Battery voltage (power input 1).',
                'SPN Position in PGN': '5-6',
                'SPN Length': '16 bits',
                'Resolution': '0.05 V/bit',
                'Offset': '0',
                'Data Range': '0 to 3212.75 V',
                'Operational Range': None,
                'Units': 'V',
                'start_byte': 4,
                'start_bit': 0,
                'length_bits': 16,
                'scale': 0.05,
                'n_decimals': 2,
                'offset': 0,
                'min_value': 0,
                'max_value': 3212.75,
                'unit': 'V',
            },
            158: {
                'SPN Name': 'Key Switch Battery Potential',
                'SPN Description': 'Voltage measured at the input of the key switch.',
                'SPN Position in PGN': '7-8',
                'SPN Length': '16 bits',
                'Resolution': '0.05 V/bit',
                'Offset': '0',
                'Data Range': '0 to 3212.75 V',
                'Operational Range': None,
                'Units': 'V',
                'start_byte': 6,
                'start_bit': 0,
                'length_bits': 16,
                'scale': 0.05,
                'n_decimals': 2,
                'offset': 0,
                'min_value': 0,
                'max_value': 3212.75,
                'unit': 'V',
            },
        },
    }

    # ─── PGN 65265 (0xFEF1) — CCVS: Cruise Control/Vehicle Speed ───
    spec[65265] = {
        'Parameter Group Label': 'Cruise Control/Vehicle Speed',
        'Acronym': 'CCVS',
        'PGN Description': 'Vehicle speed and cruise control status.',
        'PGN Data Length': 8,
        'Default Priority': 6,
        'Transmission Rate': '100 ms',
        'transmission_rate_ms': 100,
        'SPNs': {
            84: {
                'SPN Name': 'Wheel-Based Vehicle Speed',
                'SPN Description': 'Speed of the vehicle as calculated from wheel or transmission output speed.',
                'SPN Position in PGN': '2-3',
                'SPN Length': '16 bits',
                'Resolution': '1/256 km/h per bit',
                'Offset': '0',
                'Data Range': '0 to 250.996 km/h',
                'Operational Range': None,
                'Units': 'km/h',
                'start_byte': 1,
                'start_bit': 0,
                'length_bits': 16,
                'scale': 1 / 256,
                'n_decimals': 4,
                'offset': 0,
                'min_value': 0,
                'max_value': 250.996,
                'unit': 'km/h',
            },
        },
    }

    # ─── PGN 65269 (0xFEF5) — AMB: Ambient Conditions ───
    spec[65269] = {
        'Parameter Group Label': 'Ambient Conditions',
        'Acronym': 'AMB',
        'PGN Description': 'Ambient temperature and barometric pressure.',
        'PGN Data Length': 8,
        'Default Priority': 6,
        'Transmission Rate': '1 s',
        'transmission_rate_ms': 1000,
        'SPNs': {
            108: {
                'SPN Name': 'Barometric Pressure',
                'SPN Description': 'Absolute air pressure of the atmosphere.',
                'SPN Position in PGN': '1',
                'SPN Length': '8 bits',
                'Resolution': '0.5 kPa/bit',
                'Offset': '0',
                'Data Range': '0 to 125 kPa',
                'Operational Range': None,
                'Units': 'kPa',
                'start_byte': 0,
                'start_bit': 0,
                'length_bits': 8,
                'scale': 0.5,
                'n_decimals': 1,
                'offset': 0,
                'min_value': 0,
                'max_value': 125,
                'unit': 'kPa',
            },
            171: {
                'SPN Name': 'Ambient Air Temperature',
                'SPN Description': 'Temperature of the ambient air.',
                'SPN Position in PGN': '4-5',
                'SPN Length': '16 bits',
                'Resolution': '0.03125 deg C/bit',
                'Offset': '-273',
                'Data Range': '-273 to 1735 deg C',
                'Operational Range': None,
                'Units': 'deg C',
                'start_byte': 3,
                'start_bit': 0,
                'length_bits': 16,
                'scale': 0.03125,
                'n_decimals': 5,
                'offset': -273,
                'min_value': -273,
                'max_value': 1735,
                'unit': 'deg C',
            },
        },
    }

    # ─── PGN 65253 (0xFEE5) — EH: Engine Hours, Revolutions ───
    spec[65253] = {
        'Parameter Group Label': 'Engine Hours, Revolutions',
        'Acronym': 'EH',
        'PGN Description': 'Accumulated engine hours and revolutions.',
        'PGN Data Length': 8,
        'Default Priority': 6,
        'Transmission Rate': '1 s',
        'transmission_rate_ms': 1000,
        'SPNs': {
            247: {
                'SPN Name': 'Engine Total Hours of Operation',
                'SPN Description': 'Accumulated time of operation of engine.',
                'SPN Position in PGN': '1-4',
                'SPN Length': '32 bits',
                'Resolution': '0.05 hr/bit',
                'Offset': '0',
                'Data Range': '0 to 210554060.75 hr',
                'Operational Range': None,
                'Units': 'hr',
                'start_byte': 0,
                'start_bit': 0,
                'length_bits': 32,
                'scale': 0.05,
                'n_decimals': 2,
                'offset': 0,
                'min_value': 0,
                'max_value': 100000,
                'unit': 'hr',
            },
        },
    }

    return spec


def get_default_tx_pgns_spns():
    """Return the default PGN→SPN mapping for engine simulation."""
    return {
        61444: [899, 513, 190, 512],         # EEC1
        61443: [91, 92, 974],                 # EEC2
        65262: [110, 174, 175],               # ET1
        65263: [94, 22, 100, 109],            # EFL/P1
        65266: [183, 184],                    # LFE1
        65270: [102, 105, 106],               # IC1
        65271: [168, 158],                    # VEP1
        65265: [84],                          # CCVS
        65269: [108, 171],                    # AMB
        65253: [247],                         # EH
    }
